### PR TITLE
Splash Screen Completed + Package Issues fixed with widget test

### PR DESCRIPTION
**Pull request by tanmoysrt**
The boilerplate has some issues which can affect other contributors to contribute in the project

List of Issues that has been Fixed 

-  Issues in pubspec.ymlfixed
- widget_test was throwing error due to some changes in main.dart file
- Project is now compaitable for any flutter stable version >=2.18.2

### CODE REVIEW

**Comment by tanmoysrt** [comment]
@destrex271 merge this one ,  so that other contributors dont face issue while working on this

**Comment by tanmoysrt** [comment]
Splash screen completed

Themes implemented
- [x] Light theme
- [x] Dark theme

### Preview
##### Dark Theme based
WhatsApp Image 2022-10-10 at 23 06 20


#####  Light Theme based
WhatsApp Image 2022-10-10 at 23 06 19

**Comment by tanmoysrt** [comment]
@destrex271 Please review and merge

**Comment by destrex271** [comment]
Amazing Work!

**Comment by tanmoysrt** [comment]
> Amazing Work!

Thanks

**Pull request merged**
